server:
  port: 8080
  tomcat:
    additional-tld-skip-patterns: '*mchange-commons-java*.jar'
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.190:3316/jpa
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
dubbo:
  application:
    name: ruilexiong-index-web
  registry:
    address: zookeeper://192.168.43.190:2281


